import appFlowy from '../assets/images/OpenSrc/appflowy.png';
import flood from "../assets/images/OpenSrc/flood.png";
import mattermost from '../assets/images/OpenSrc/mattermost.jfif';
import openFoodFacts from '../assets/images/OpenSrc/openFoodFacts.png';

import {
    SiFlutter,
    SiPython,
    SiReact,
    SiTypescript,
    TbBrandReactNative
} from "react-icons/all";

export const OPEN_SOURCE_CONTRIBUTIONS = [
  {
    id: "os-1",
    organisation: "openfoodfacts",
    logo: openFoodFacts,
    repo: "smooth-app",
    type: "pull-request",
    status: "merged",
    title:
      'Make "Start Scanning" Button',
    link: "https://github.com/openfoodfacts/smooth-app/pull/3569",
    number: "#3569",
    date: "Jan 12 2023",
    linesAdded: "34",
    linesDeleted: "29",
    technology: SiFlutter,
  },
  {
    id: "os-2",
    organisation: "openfoodfacts",
    logo: openFoodFacts,
    repo: "smooth-app",
    type: "pull-request",
    status: "merged",
    title: "Pop dialog navigator properly",
    link: "https://github.com/openfoodfacts/smooth-app/pull/3528",
    number: "#3538",
    date: "Jan 5 2023",
    linesAdded: "1",
    linesDeleted: "1",
    technology: SiFlutter,
  },
  {
    id: "os-3",
    organisation: "openfoodfacts",
    logo: openFoodFacts,
    repo: "smooth-app",
    type: "pull-request",
    status: "merged",
    title: "fab appearing in start scanning page",
    link: "https://github.com/openfoodfacts/smooth-app/pull/3550",
    number: "#3550",
    date: "Jan 8 2023",
    linesAdded: "1",
    linesDeleted: "1",
    technology: SiFlutter,
  },
  {
    id: "os-4",
    organisation: "openfoodfacts",
    logo: openFoodFacts,
    repo: "smooth-app",
    type: "pull-request",
    status: "merged",
    title: "feat: add troubleshooting section",
    link: "https://github.com/openfoodfacts/smooth-app/pull/3587",
    number: "#3587",
    date: "Jan 18 2023",
    linesAdded: "16",
    linesDeleted: "1",
    technology: SiFlutter,
  },
  {
    id: "os-5",
    organisation: "openfoodfacts",
    logo: openFoodFacts,
    repo: "smooth-app",
    type: "pull-request",
    status: "merged",
    title: "String with only spaces is considered as name !",
    link: "https://github.com/openfoodfacts/smooth-app/pull/3593",
    number: "#3593",
    date: "Jan 18 2023",
    linesAdded: "3",
    linesDeleted: "2",
    technology: SiFlutter,
  },
  {
    id: "os-6",
    organisation: "openfoodfacts",
    logo: openFoodFacts,
    repo: "smooth-app",
    type: "pull-request",
    status: "merged",
    title: "Alternate the color between packaging components to avoid any potential confusion",
    link: "https://github.com/openfoodfacts/smooth-app/pull/3619",
    number: "#3619",
    date: "Jan 23 2023",
    linesAdded: "22",
    linesDeleted: "1",
    technology: SiFlutter,
  },
  {
    id: "os-7",
    organisation: "openfoodfacts",
    logo: openFoodFacts,
    repo: "smooth-app",
    type: "pull-request",
    status: "merged",
    title: "Add undo option when product in list deleted!",
    link: "https://github.com/openfoodfacts/smooth-app/pull/3648",
    number: "#3648",
    date: "Jan 30 2023",
    linesAdded: "23",
    linesDeleted: "4",
    technology: SiFlutter,
  },
  {
    id: "os-8",
    organisation: "openfoodfacts",
    logo: openFoodFacts,
    repo: "hunger-games",
    type: "pull-request",
    status: "merged",
    title: "No intuitive way to close a modal on mobile",
    link: "https://github.com/openfoodfacts/hunger-games/pull/495",
    number: "#495",
    date: "Jan 31 2023",
    linesAdded: "27",
    linesDeleted: "2",
    technology: SiReact,
  },
  {
    id: "os-9",
    organisation: "openfoodfacts",
    logo: openFoodFacts,
    repo: "smooth-app",
    type: "pull-request",
    status: "merged",
    title: "Email sender application broken",
    link: "https://github.com/openfoodfacts/smooth-app/pull/3649",
    number: "#3649",
    date: "Jan 29 2023",
    linesAdded: "6",
    linesDeleted: "0",
    technology: SiFlutter,
  },
  {
    id: "os-10",
    organisation: "openfoodfacts",
    logo: openFoodFacts,
    repo: "smooth-app",
    type: "pull-request",
    status: "merged",
    title: "feat: Add copy to clipBoard button in send email manually when user has no email application",
    link: "https://github.com/openfoodfacts/smooth-app/pull/3651",
    number: "#3651",
    date: "Feb 8 2023",
    linesAdded: "63",
    linesDeleted: "11",
    technology: SiFlutter,
  },
  {
    id: "os-11",
    organisation: "openfoodfacts",
    logo: openFoodFacts,
    repo: "hunger-games",
    type: "pull-request",
    status: "merged",
    title: "Capitalize countries",
    link: "https://github.com/openfoodfacts/hunger-games/pull/522",
    number: "#522",
    date: "Feb 5 2023",
    linesAdded: "35",
    linesDeleted: "6",
    technology: SiReact,
  },
  {
    id: "os-12",
    organisation: "openfoodfacts",
    logo: openFoodFacts,
    repo: "hunger-games",
    type: "pull-request",
    status: "merged",
    title: "feat: add loading animation before question display",
    link: "https://github.com/openfoodfacts/hunger-games/pull/498",
    number: "#498",
    date: "Jan 31 5 2023",
    linesAdded: "14",
    linesDeleted: "3",
    technology: SiReact,
  },
  {
    id: "os-13",
    organisation: "openfoodfacts",
    logo: openFoodFacts,
    repo: "hunger-games",
    type: "pull-request",
    status: "merged",
    title: "fix: selectAll in logo game",
    link: "https://github.com/openfoodfacts/hunger-games/pull/530",
    number: "#530",
    date: "Feb 5 2023",
    linesAdded: "6",
    linesDeleted: "1",
    technology: SiReact,
  },
  {
    id: "os-14",
    organisation: "openfoodfacts",
    logo: openFoodFacts,
    repo: "smooth-app",
    type: "pull-request",
    status: "merged",
    title: "feat: format sign_up_errors to normal texts instead of HTML format",
    link: "https://github.com/openfoodfacts/smooth-app/pull/3692",
    number: "#3692",
    date: "Feb 16 2023",
    linesAdded: "33",
    linesDeleted: "13",
    technology: SiFlutter,
  },
  {
    id: "os-15",
    organisation: "openfoodfacts",
    logo: openFoodFacts,
    repo: "smooth-app",
    type: "pull-request",
    status: "merged",
    title: "feat: Improve user profile UI",
    link: "https://github.com/openfoodfacts/smooth-app/pull/3693",
    number: "#3693",
    date: "Feb 16 2023",
    linesAdded: "28",
    linesDeleted: "29",
    technology: SiFlutter,
  },
  {
    id: "os-16",
    organisation: "openfoodfacts",
    logo: openFoodFacts,
    repo: "smooth-app",
    type: "pull-request",
    status: "merged",
    title: "refactor: move usermanagement provider after if check!",
    link: "https://github.com/openfoodfacts/smooth-app/pull/3698",
    number: "#3698",
    date: "Feb 16 2023",
    linesAdded: "3",
    linesDeleted: "2",
    technology: SiFlutter,
  },
  {
    id: "os-17",
    organisation: "openfoodfacts",
    logo: openFoodFacts,
    repo: "hunger-games",
    type: "pull-request",
    status: "merged",
    title: "feat: Common footer module.",
    link: "https://github.com/openfoodfacts/hunger-games/pull/539",
    number: "#539",
    date: "Feb 14 2023",
    linesAdded: "565",
    linesDeleted: "90",
    technology: SiReact,
  },
  {
    id: "os-18",
    organisation: "openfoodfacts",
    logo: openFoodFacts,
    repo: "smooth-app",
    type: "pull-request",
    status: "merged",
    title: "feat: add rate the app link and share the app link in the settings page!",
    link: "https://github.com/openfoodfacts/smooth-app/pull/3704",
    number: "#3704",
    date: "Feb 21 2023",
    linesAdded: "111",
    linesDeleted: "0",
    technology: SiFlutter,
  },
  {
    id: "os-19",
    organisation: "openfoodfacts",
    logo: openFoodFacts,
    repo: "smooth-app",
    type: "pull-request",
    status: "merged",
    title: "fix: checkBox not showing right mark in dark theme",
    link: "https://github.com/openfoodfacts/smooth-app/pull/3725",
    number: "#3725",
    date: "Feb 21 2023",
    linesAdded: "2",
    linesDeleted: "0",
    technology: SiFlutter,
  },
  {
    id: "os-20",
    organisation: "openfoodfacts",
    logo: openFoodFacts,
    repo: "smooth-app",
    type: "pull-request",
    status: "merged",
    title: "feat: make nutrient search accentuation insensitive",
    link: "https://github.com/openfoodfacts/smooth-app/pull/3792",
    number: "#3792",
    date: "Mar 21 2023",
    linesAdded: "7",
    linesDeleted: "3",
    technology: SiFlutter,
  },
  {
    id: "os-21",
    organisation: "openfoodfacts",
    logo: openFoodFacts,
    repo: "smooth-app",
    type: "pull-request",
    status: "merged",
    title: "fix: remove validation check for basic info fields",
    link: "https://github.com/openfoodfacts/smooth-app/pull/3794",
    number: "#3794",
    date: "Apr 8 2023",
    linesAdded: "12",
    linesDeleted: "28",
    technology: SiFlutter,
  },
  {
    id: "os-22",
    organisation: "openfoodfacts",
    logo: openFoodFacts,
    repo: "smooth-app",
    type: "pull-request",
    status: "merged",
    title: "fix: visual inconsistency in app_settings",
    link: "https://github.com/openfoodfacts/smooth-app/pull/3818",
    number: "#3818",
    date: "Apr 8 2023",
    linesAdded: "77",
    linesDeleted: "49",
    technology: SiFlutter,
  },
  {
    id: "os-23",
    organisation: "openfoodfacts",
    logo: openFoodFacts,
    repo: "rate-my-recipe",
    type: "pull-request",
    status: "merged",
    title: "chore: refactor and enhancement",
    link: "https://github.com/openfoodfacts/rate-my-recipe/pull/27",
    number: "#27",
    date: "Jun 19 2023",
    linesAdded: "28",
    linesDeleted: "13",
    technology: SiReact,
  },
  {
    id: "os-24",
    organisation: "openfoodfacts",
    logo: openFoodFacts,
    repo: "hunger-games",
    type: "pull-request",
    status: "merged",
    title: "feat: Add lazy import for different routes",
    link: "https://github.com/openfoodfacts/hunger-games/pull/656",
    number: "#656",
    date: "Jul 9 2023",
    linesAdded: "660",
    linesDeleted: "600",
    technology: SiReact,
  },
  {
    id: "os-25",
    organisation: "openfoodfacts",
    logo: openFoodFacts,
    repo: "smooth-app",
    type: "pull-request",
    status: "merged",
    title: "feat: Create a screen listing all attributes for a product",
    link: "https://github.com/openfoodfacts/smooth-app/pull/4714",
    number: "#4714",
    date: "Nov 4 2023",
    linesAdded: "354",
    linesDeleted: "39",
    technology: SiReact,
  },
  {
    id: "os-26",
    organisation: "openfoodfacts",
    logo: openFoodFacts,
    repo: "open-prices",
    type: "pull-request",
    status: "merged",
    title: "feat: add endpoint to update price ",
    link: "https://github.com/openfoodfacts/open-prices/pull/202",
    number: "#202",
    date: "Feb 23 2024",
    linesAdded: "107",
    linesDeleted: "0",
    technology: SiPython,
  },
  {
    id: "os-101",
    organisation: "mattermost",
    logo: mattermost,
    repo: "mattermost-mobile",
    type: "pull-request",
    status: "merged",
    title: "fix: reset password bug",
    link: "https://github.com/mattermost/mattermost-mobile/pull/7135",
    number: "#7135",
    date: "Feb 16 2023",
    linesAdded: "3",
    linesDeleted: "4",
    technology: TbBrandReactNative,
  },
  {
    id: "os-102",
    organisation: "mattermost",
    logo: mattermost,
    repo: "mattermost-mobile",
    type: "pull-request",
    status: "merged",
    title: "Feat: add copy to clipboard button in \"about\" mattermost page",
    link: "https://github.com/mattermost/mattermost-mobile/pull/7134",
    number: "#7134",
    date: "Jul 26 2023",
    linesAdded: "73",
    linesDeleted: "37",
    technology: TbBrandReactNative,
  },
  {
    id: "os-103",
    organisation: "mattermost",
    logo: mattermost,
    repo: "mattermost",
    type: "pull-request",
    status: "merged",
    title: "Migrate \"advanced_create_post.test.jsx\" to Typescript",
    link: "https://github.com/mattermost/mattermost/pull/24955",
    number: "#24955",
    date: "Oct 24 2023",
    linesAdded: "471",
    linesDeleted: "232",
    technology: SiTypescript,
  },
  {
    id: "os-104",
    organisation: "mattermost",
    logo: mattermost,
    repo: "mattermost",
    type: "pull-request",
    status: "merged",
    title: "Migrate \"interactive_dialog.jsx\" and tests to Typescript",
    link: "https://github.com/mattermost/mattermost/pull/25026",
    number: "#25026",
    date: "Oct 28 2023",
    linesAdded: "88",
    linesDeleted: "56",
    technology: SiTypescript,
  },
  {
    id: "os-105",
    organisation: "mattermost",
    logo: mattermost,
    repo: "mattermost",
    type: "pull-request",
    status: "merged",
    title: "Replace usage of LocalizedIcon in 'plain_log_list.tsx' with i/span tags",
    link: "https://github.com/mattermost/mattermost/pull/25135",
    number: "#25135",
    date: "Oct 31 2023",
    linesAdded: "8",
    linesDeleted: "9",
    technology: SiReact,
  },
  {
    id: "os-106",
    organisation: "mattermost",
    logo: mattermost,
    repo: "mattermost",
    type: "pull-request",
    status: "merged",
    title: "Replace usage of LocalizedIcon in 'rhs_header_post.tsx' with i/span tags",
    link: "https://github.com/mattermost/mattermost/pull/25159",
    number: "#25159",
    date: "Oct 27 2023",
    linesAdded: "15",
    linesDeleted: "14",
    technology: SiReact,
  },
  {
    id: "os-107",
    organisation: "mattermost",
    logo: mattermost,
    repo: "mattermost",
    type: "pull-request",
    status: "merged",
    title: " Migrate 'switch_channel_provider.test.jsx' to TypeScript",
    link: "https://github.com/mattermost/mattermost/pull/25210",
    number: "#25210",
    date: "Oct 31 2023",
    linesAdded: "63",
    linesDeleted: "53",
    technology: SiTypescript,
  },
  {
    id: "os-201",
    organisation: "CCExtractor",
    logo: flood,
    repo: "Flood_Mobile",
    type: "pull-request",
    status: "merged",
    title: "fix: make checkbox clearly visible onclick",
    link: "https://github.com/CCExtractor/Flood_Mobile/pull/160",
    number: "#160",
    date: "Jan 20 2023",
    linesAdded: "133",
    linesDeleted: "105",
    technology: SiFlutter,
  },
  {
    id: "os-301",
    organisation: "AppFlowy-IO",
    logo: appFlowy,
    repo: "AppFlowy",
    type: "pull-request",
    status: "merged",
    title: "feat: add icon to dropdown button in language view",
    link: "https://github.com/AppFlowy-IO/AppFlowy/pull/2031",
    number: "#2031",
    date: "Mar 20 2023",
    linesAdded: "24",
    linesDeleted: "23",
    technology: SiFlutter,
  },
];